name: Catch OpenAI API key

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout

    - name: Setup Python
      uses: actions/setup-python
      with:
        python-version: 3.11
  

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ./src/

    - name: Run Python script with secret
      env:
        APIKEY: ${{ secrets.APIKEY }}
      run: |
        python main.py

  